title: Civic Futures Summit / Central Texas - October 1-2, 2019
description: Weâ€™re bringing together governments and universities across central texas to celebrate and share skills and ideas for the future of state and local government

repository: civic-imagination/summit-website.git
github.pages_hostname: https://civicfutures.io

markdown: kramdown
highlighter: rouge
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]

baseurl: /
port: 4060
url: //civicfutures.io
twitter_handle: civicimagination


# Define some defaults
defaults:
  -
    values:
      layout: "page"
      author: "Civic Futures Summit"


# Permalink Configuration
permalink: /blog/:year/:month/:title

# Post types
collections:
  team:
    output: true
    permalink: /team/:name
  events:
    output: false
    permalink: /events/:name

# Exclude from _site build
exclude: ['.git',
  '.gitignore',
  'Gemfile',
  'Gemfile.lock',
  'CNAME',
  'LICENSE',
  'feed.xml',
  'team/README.md'
  ]


# Setting relative permalink to false. See http://jekyllrb.com/docs/upgrading/.
relative_permalinks: false

sass:
  sass_dir: _sass


# Plugins and extras
plugins:
- jekyll-autoprefixer
- jekyll-github-metadata
